account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name = 'account'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(next_page='shop:home'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
    path('edit/',views.edit,name='edit'),
    path('profile/',views.profile,name='profile'),
    path('order_list/',views.order_list,name='order_list'),
   
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.remove,name='cart_remove'),
]

favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'


urlpatterns = [
    path('all/',views.all,name='all'),
    path('clear/',views.clear,name='clear'),
    path('favourites/add_to_fav/<int:product_id>/', views.add_to_fav, name='add_to_fav'),
    path('favourites/remove_to_fav/<int:product_id>/', views.remove_to_fav, name='remove_to_fav'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
     path('social-auth/',include('social_django.urls', namespace='social')),

    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('favourites/',include('favourites.urls',namespace='favourites')),
    path('',include('shop.urls',namespace='shop')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
                                        name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',
 views.admin_order_pdf,
 name='admin_order_pdf'),
]

shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'


urlpatterns = [
    path('',views.home,name='home'),
    path('search/',views.product_search,name='search'),
    path('list/',views.product_list,name='list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
  
]

shop/models.py
from django.db import models
from django.urls import reverse


class Caterogy(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300,unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields = ['name']),

        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category",args=[self.slug])    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(available=True)
    
class Product(models.Model):
    category = models.ForeignKey(Caterogy,related_name='products',on_delete = models.CASCADE)
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300)
    description = models.TextField()
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    published = ProductManager()
    objects = ProductManager()

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail",args=[self.id,self.slug])

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()
    

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Caterogy,Product
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from .forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity

def product_list(request,category_slug = None):
    category = None
    categories = Caterogy.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Caterogy,slug=category_slug)
        products = products.filter(category=category)
    return render(request,'shop/product/list.html',{'category':category,'categories':categories,'products':products})

@login_required
def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    return render(request,'shop/product/detail.html',{'product':product,'cart_product_form':cart_product_form})

def home(request):
    return render(request,'shop/home.html')

def product_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Product.published.annotate(
                similarity=TrigramSimilarity('name', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,'shop/product/list.html',{'form':form,'query':query,'results':results})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{%load static %}

{%block content%}
<style>
    body {
        background-image: url('https://cdn.steamstatic.com/steamcommunity/public/images/items/447120/f173d53b9c696240fba8c45b6ec735f7bc1ce01a.jpg');
        color: #ffffff; /* Цвет текста по умолчанию */
    }
    
    .card-title {
        font-size: 1.25rem;
        color: #00ffb6; /* Цвет заголовков карточек */
    }
    
    .card-text {
        font-size: 0.9rem;
        color: #9fffd3; /* Цвет описания товара */
    }
    
    .aspect-ratio {
        position: relative;
        width: 100%;
        height: 0;
        padding-top: 100%; /* Соотношение сторон 1:1 */
    }
    
    .custom-shadow {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5); /* Темная тень для карточек */
    }
    
</style>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url "shop:home"%}">Harmony of Esotericism</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">f</span>
        </button>
        <div class="collapse navbar-collapse show" id="navbarDark">
            <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url "shop:list"%}">Товары</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{%url "cart:cart_detail"%}">Корзина</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{%url "favourites:all"%}">Избранные</a>
              </li>
             
                <div class="nav-item dropdown">
                 
                  <a class=" nav-link active dropdown-toggle" tabindex="-1" aria-disabled="true" id="dropdownMenuDark" data-bs-toggle="dropdown" >
                        Пользователь
                  </a>
                  
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuDark">
                      {% if request.user.is_authenticated %}
                      <li class="nav-item">
                          <span class="navbar-text">
                              🕉️ Welcome, <strong>{{ request.user.first_name|default:request.user.username }}</strong> ✨
                          </span>
                      </li>
                      <li><a class="dropdown-item" href="{%url "account:profile"%}">Мой Профиль</a></li>
                        <li><a class="dropdown-item" href="{%url "account:logout"%}">Выйти</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{%url "account:login"%}">Войти</a></li>
                        {% endif %}
                    </ul>
                </div>
            </ul>
          
          
        </div>
    </div>
</nav>

<div class="product-detail-page d-flex flex-column flex-md-row align-items-center justify-content-center text-light" style="min-height: 100vh;">
    <div class="product-image-container text-center mb-4 mb-md-0" style="max-width: 300px;">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}" class="product-image img-fluid rounded" style="max-height: 300px; object-fit: cover;">
    </div>
    <div class="product-info-container text-center ms-md-5">
        <div class="product-detail mystical-background p-4 border rounded">
            <h1 class="display-5">{{ product.name }}</h1>
            <p class="product-price h4">{{ product.price }}₸</p>
            <p class="product-description">{{ product.description|linebreaks }}</p>
            <div class="product-actions mt-4">
                <form action="{%url "cart:cart_add" product.id%}" method="post" class="mb-3">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart">
                </form>
                <div>
                    <a href="{% url 'shop:list' %}" class="btn btn-outline-light me-2">Продолжить покупки</a>
                    <a href="{% url "orders:order_create" %}" class="btn btn-outline-light">Оформить заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>

</div>




{%endblock%}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{%block content%}
<style>
    body {
        background-image: url('https://cdn.steamstatic.com/steamcommunity/public/images/items/447120/f173d53b9c696240fba8c45b6ec735f7bc1ce01a.jpg');
        color: #ffffff; /* Цвет текста по умолчанию */
    }
    
    .card-title {
        font-size: 1.25rem;
        color: #00ffb6; /* Цвет заголовков карточек */
    }
    
    .card-text {
        font-size: 0.9rem;
        color: #9fffd3; /* Цвет описания товара */
    }
    
    .aspect-ratio {
        position: relative;
        width: 100%;
        height: 0;
        padding-top: 100%; /* Соотношение сторон 1:1 */
    }
    
    .custom-shadow {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5); /* Темная тень для карточек */
    }
    
    
</style>

    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <div class="container-fluid">
          <a class="navbar-brand" href="{%url "shop:home"%}">Harmony of Esotericism</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon">f</span>
          </button>
          <div class="collapse navbar-collapse show" id="navbarDark">
              <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                  <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{%url "shop:list"%}">Товары</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link active" href="{%url "cart:cart_detail"%}">Корзина</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{%url "favourites:all"%}">Избранные</a>
                </li>
               
                  <div class="nav-item dropdown">
                   
                    <a class=" nav-link active dropdown-toggle" tabindex="-1" aria-disabled="true" id="dropdownMenuDark" data-bs-toggle="dropdown" >
                          Пользователь
                    </a>
                    
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuDark">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">
                                🕉️ Welcome, <strong>{{ request.user.first_name|default:request.user.username }}</strong> ✨
                            </span>
                        </li>
                        <li><a class="dropdown-item" href="{%url "account:profile"%}">Мой Профиль</a></li>
                          <li><a class="dropdown-item" href="{%url "account:logout"%}">Выйти</a></li>
                          {% else %}
                          <li><a class="dropdown-item" href="{%url "account:login"%}">Войти</a></li>
                          {% endif %}
                      </ul>
                  </div>
              </ul>
            
            
          </div>
      </div>
  </nav>

  <div class="container my-5">
    <div class="row">
        <!-- Sidebar with Categories -->
        <div id="sidebar" class="col-md-3 mb-4" style="background: #000000ad;">
            <div class="btn-group-vertical w-100" role="group" aria-label="Categories">
                <a href="{% url 'shop:list' %}" class="btn btn-outline-secondary {% if not category %}active{% endif %}">
                    All Categories
                </a>
                {% for c in categories %}
                <a href="{{ c.get_absolute_url }}" class="btn btn-outline-secondary {% if category and category.slug == c.slug %}active{% endif %}">
                    {{ c.name }}
                </a>
                {% endfor %}
            </div>
        </div>

        <!-- Main Content with Products and Search Form -->
        <div id="main" class="col-md-9">
            <!-- Search Form -->
            <form class="d-flex mb-4" action="{% url 'shop:search' %}" method="get">
                <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>

            <!-- Display Results Based on Search or Category -->
            <div class="row">
                {% if query %}
                    <h2 class="text-white">Results for "{{ query }}":</h2>
                    {% if results %}
                        {% for product in results %}
                        <div class="col-12 col-md-6 col-lg-4 mb-4">
                            <div class="card h-100 border-primary rounded custom-shadow" style="background: #000000a3;">
                                <!-- Product Image -->
                                {% if product.image %}
                                <a href="{{ product.get_absolute_url }}">
                                    <div class="aspect-ratio overflow-hidden" style="position: relative; padding-top: 100%;">
                                        <img src="{{ product.image.url }}" class="w-100 h-100 position-absolute" style="object-fit: cover; top: 0; left: 0;" alt="{{ product.name }}">
                                    </div>
                                </a>
                                {% else %}
                                <div class="aspect-ratio overflow-hidden" style="position: relative; padding-top: 100%;">
                                    <img src="{% static 'deps/img/no_image.jpg' %}" class="w-100 h-100 position-absolute" style="object-fit: cover; top: 0; left: 0;" alt="{{ product.name }}">
                                </div>
                                {% endif %}
                                
                                <!-- Product Description -->
                                <div class="card-body">
                                    <a href="{{ product.get_absolute_url }}" class="text-white" style="text-decoration:none">
                                        <h5 class="card-title">{{ product.name }}</h5>
                                    </a>
                                    <p class="card-text text-truncate" style="color: white">{{ product.description }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <p><strong style="color: white">{{ product.price }}₸</strong></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <p class="text-white">No results found for "{{ query }}".</p>
                    {% endif %}
                {% else %}
                    {% for product in products %}
                    <div class="col-12 col-md-6 col-lg-4 mb-4">
                        <div class="card h-100 border-primary rounded custom-shadow" style="background: #000000a3;">
                            <!-- Product Image -->
                            {% if product.image %}
                            <a href="{{ product.get_absolute_url }}">
                                <div class="aspect-ratio overflow-hidden" style="position: relative; padding-top: 100%;">
                                    <img src="{{ product.image.url }}" class="w-100 h-100 position-absolute" style="object-fit: cover; top: 0; left: 0;" alt="{{ product.name }}">
                                </div>
                            </a>
                            {% else %}
                            <div class="aspect-ratio overflow-hidden" style="position: relative; padding-top: 100%;">
                                <img src="{% static 'deps/img/no_image.jpg' %}" class="w-100 h-100 position-absolute" style="object-fit: cover; top: 0; left: 0;" alt="{{ product.name }}">
                            </div>
                            {% endif %}
                            
                            <!-- Product Description -->
                            <div class="card-body">
                                <a href="{{ product.get_absolute_url }}" class="text-white" style="text-decoration:none">
                                    <h5 class="card-title">{{ product.name }}</h5>
                                </a>
                                <p class="card-text text-truncate" style="color: white">{{ product.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <p><strong style="color: white">{{ product.price }}₸</strong></p>
                                </div>
                                <form action="{% if product in user.favorites.all %}{% url 'favourites:remove_to_fav' product.id %}{% else %}{% url 'favourites:add_to_fav' product.id %}{% endif %}" method="post" class="favorite-form">
                                    {% csrf_token %}
                                    <button type="button" 
                                    class="btn btn-outline-light favorite-btn {% if product in user.favorites.all %}favorited{% endif %}" 
                                    data-product-id="{{ product.id }}" 
                                    onclick="toggleFavorite(this)">
                                <svg class="heart-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="{% if product  in user.favorites.all %}red{% else %}white{% endif %}" viewBox="0 0 24 24">
                                    <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                                </svg>
                            </button>
                            
                                </form>
                                
                            </div>
                        </div>
                        
                    </div>
                    {% endfor %}
                {% endif %}
            </div>

            <!-- Pagination (if needed) -->
            {% if products.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% for page_num in products.paginator.page_range %}
                            <li class="page-item {% if products.number == page_num %}active{% endif %}">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>

<script>
    function toggleFavorite(button) {
        const productId = button.getAttribute('data-product-id');
        const isFavorited = button.classList.contains('favorited');
        const url = isFavorited 
                    ? "{% url 'favourites:remove_to_fav' 0 %}".replace("0", productId)
                    : "{% url 'favourites:add_to_fav' 0 %}".replace("0", productId);

        fetch(url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({})
        })
        .then(response => {
            if (response.ok) {
                // Toggle the `favorited` class on the button
                button.classList.toggle('favorited');

                // Update icon color based on new favorited state
                const icon = button.querySelector('svg');
                if (button.classList.contains('favorited')) {
                    icon.setAttribute('fill', 'red'); // Filled state
                }
            }
        });
    }
</script>

    
{%endblock%}